services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=Root1234
      - MYSQL_DATABASE=db_dod
    volumes: 
      - db-data:/var/lib/mysql

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"          # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    restart: always
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=0
      - DATA_DIR=/var/lib/localstack
    volumes: 
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes: 
  db-data:
    driver: local
  localstack-data:
    driver: local
